ProgettoTest/ViewModels/DashboardViewModel.cs
using ProgettoTest.Models;

namespace ProgettoTest.ViewModels
{
    public class DashboardViewModel
    {
        public List<Race> Races { get; set; }
        public List<Club> Clubs { get; set; }
    }
}

ProgettoTest/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using ProgettoTest.Data;
using ProgettoTest.Extensions;
using ProgettoTest.Interfaces;
using ProgettoTest.Models;
using ProgettoTest.ViewModels;

namespace ProgettoTest.Controllers
{
    public class ClubController : Controller
    {
        private readonly IClubRepository _clubRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ClubController(IClubRepository clubRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _clubRepository = clubRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        #region Get All
        public async Task<IActionResult> Index(string sortOrder, int page = 1)
        {
            ViewData["CurrentSort"] = sortOrder;

            ViewData["TitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["LocationSortParm"] = sortOrder == "Location" ? "location_desc" : "Location";

            var clubs = _clubRepository.GetAll();

            switch (sortOrder)
            {
                case "title_desc":
                    clubs = clubs.OrderByDescending(c => c.Title);
                    break;
                default:
                    clubs = clubs.OrderBy(c => c.Title);
                    break;
            }

            var pagedClubs = await clubs.ToPagedListAsync(page, 3);
            return View(pagedClubs);
        }
        #endregion

        #region Get By Id
        public async Task<IActionResult> Detail(int id)
        {
            var club = await _clubRepository.GetByIdAsync(id);

            return View(club);
        }
        #endregion

        #region Create
        public IActionResult Create() 
        {
            var currentUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createClubVM = new CreateClubViewModel()
            {
                AppUserId = currentUserId
            };
            return View(createClubVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateClubViewModel clubVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(clubVM.Image);

                var club = new Club
                {
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = result.Url.ToString(),
                    AppUserId = clubVM.AppUserId,
                    Address = new Address
                    {
                        Street = clubVM.Address.Street,
                        City = clubVM.Address.City,
                        State = clubVM.Address.State
                    }
                };

                _clubRepository.Add(club);

                return RedirectToAction("Index");
            }
            else 
            {
                ModelState.AddModelError("", "Photo upload failed");
            }

            return View(clubVM);
        }
        #endregion

        #region Edit
        public async Task<IActionResult> Edit(int id)
        {
            var club = await _clubRepository.GetByIdAsync(id);

            if (club == null) return View("Error");

            var clubVM = new EditClubViewModel
            {
                Title = club.Title,
                Description = club.Description,
                AddressId = club.AddressId,
                Address = club.Address,
                URL = club.Image,
                ClubCategory = club.ClubCategory
            };

            return View(clubVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditClubViewModel clubVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit club");

                return View("Edit", clubVM);
            }

            var club = await _clubRepository.GetByIdAsyncNoTracking(id);

            if (club == null)
            {
                return View("Error");
            }

            if (clubVM.Image != null)
            {
                if (!string.IsNullOrEmpty(club.Image))
                {
                    try
                    {
                        await _photoService.DeletePhotoAsync(club.Image);
                    }
                    catch (Exception ex)
                    {

                        ModelState.AddModelError("", "Could not delete photo");

                        return View(clubVM);
                    }
                }

                var photoResult = await _photoService.AddPhotoAsync(clubVM.Image);
                club.Image = photoResult.Url.ToString();
            }

            club.Id = id;
            club.Title = clubVM.Title;
            club.Description = clubVM.Description;
            club.AddressId = clubVM?.AddressId;
            club.Address = clubVM.Address;

            _clubRepository.Update(club);

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);

            if (clubDetails == null) return View("Error");

            return View(clubDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteClub(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);

            if (clubDetails == null) return View("Error");

            _clubRepository.Delete(clubDetails);

            return RedirectToAction("Index");
        }
        #endregion

        #region // Prima di implementare Interfaces & Repository
        /*private readonly ApplicationDbContext _context;

        public ClubController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var clubs = _context.Clubs.ToList();

            return View(clubs);
        }

        public IActionResult Detail(int id)
        {
            var club = _context.Clubs.Include(a => a.Address).FirstOrDefault(c => c.Id == id);

            return View(club);
        }*/
        #endregion
    }
}

ProgettoTest/Controllers/DashboardController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using ProgettoTest.Interfaces;
using ProgettoTest.Models;
using ProgettoTest.ViewModels;

namespace ProgettoTest.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRespository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IPhotoService _photoService;

        public DashboardController(IDashboardRepository dashboardRespository, IHttpContextAccessor httpContextAccessor, IPhotoService photoService)
        {
            _dashboardRespository = dashboardRespository;
            _httpContextAccessor = httpContextAccessor;
            _photoService = photoService;
        }

        private void MapUserEdit(AppUser user, EditUserDashboardViewModel editVM, ImageUploadResult photoResult)
        {
            user.Id = editVM.Id;
            user.Pace = editVM.Pace;
            user.Mileage = editVM.Mileage;
            user.ProfileImageUrl = photoResult.Url.ToString();
            user.City = editVM.City;
            user.State = editVM.State;
        }

        public async Task<IActionResult> Index()
        {
            var userRaces = await _dashboardRespository.GetAllUserRaces();
            var userClubs = await _dashboardRespository.GetAllUserClubs();
            var dashboardViewModel = new DashboardViewModel()
            {
                Races = userRaces,
                Clubs = userClubs
            };
            return View(dashboardViewModel);
        }

        public async Task<IActionResult> EditUserProfile()
        {
            var currentUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var user = await _dashboardRespository.GetUserById(currentUserId);

            if (user == null) return View("Error");

            var editUserVM = new EditUserDashboardViewModel()
            {
                Id = currentUserId,
                Pace = user.Pace,
                Mileage = user.Mileage,
                ProfileImageUrl = user.ProfileImageUrl,
                City = user.City,
                State = user.State
            };

            return View(editUserVM);
        }

        [HttpPost]
        public async Task<IActionResult> EditUserProfile(EditUserDashboardViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");

                return View("EditUserProfile", editVM);
            }

            var user = await _dashboardRespository.GetByIdNoTracking(editVM.Id);

            if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null)
            {
                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _dashboardRespository.Update(user);

                return RedirectToAction("Index");
            }
            else 
            {
                try
                {
                    await _photoService.DeletePhotoAsync(user.ProfileImageUrl);
                }
                catch (Exception)
                {

                    ModelState.AddModelError("", "Could not delete photo");

                    return View(editVM);
                }

                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _dashboardRespository.Update(user);

                return RedirectToAction("Index"); 
            }
        }
    }
}

ProgettoTest/Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgettoTest.Data;
using ProgettoTest.Interfaces;
using ProgettoTest.Models;
using ProgettoTest.ViewModels;

namespace ProgettoTest.Controllers
{
    public class RaceController : Controller
    {
        private readonly IRaceRepository _raceRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public RaceController(IRaceRepository raceRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _raceRepository = raceRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        #region Get All
        public async Task<IActionResult> Index()
        {
            var races = await _raceRepository.GetAll();

            return View(races);
        }
        #endregion

        #region Get By Id
        public async Task<IActionResult> Detail(int id)
        {
            var race = await _raceRepository.GetByIdAsync(id);

            return View(race);
        }
        #endregion

        #region Create
        public IActionResult Create() 
        {
            var currentUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createRaceVM = new CreateRaceViewModel()
            {
                AppUserId = currentUserId
            };

            return View(createRaceVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRaceViewModel raceVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(raceVM.Image);

                var race = new Race
                {
                    Title = raceVM.Title,
                    Description = raceVM.Description,
                    Image = result.Url.ToString(),
                    AppUserId = raceVM.AppUserId,
                    Address = new Address
                    {
                        Street = raceVM.Address.Street,
                        City = raceVM.Address.City,
                        State = raceVM.Address.State
                    }
                };

                _raceRepository.Add(race);

                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }

            return View(raceVM);
        }
        #endregion

        #region Edit
        public async Task<IActionResult> Edit(int id)
        {
            var race = await _raceRepository.GetByIdAsync(id);

            if(race == null) return View("Error");

            var raceVM = new EditRaceViewModel
            {
                Title = race.Title,
                Description = race.Description,
                AddressId = race.AddressId,
                Address = race.Address,
                URL = race.Image,
                RaceCategory = race.RaceCategory
            };

            return View(raceVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditRaceViewModel raceVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit race");

                return View("Edit", raceVM);
            }

            var race = await _raceRepository.GetByIdAsyncNoTracking(id);

            if (race == null)
            {
                return View("Error");
            }

            if (raceVM.Image != null)
            {
                if (!string.IsNullOrEmpty(race.Image))
                {
                    try
                    {
                        await _photoService.DeletePhotoAsync(race.Image);
                    }
                    catch (Exception ex)
                    {

                        ModelState.AddModelError("", "Could not delete photo");

                        return View(raceVM);
                    }

                }

                var photoResult = await _photoService.AddPhotoAsync(raceVM.Image);
                race.Image = photoResult.Url.ToString();
            }

            race.Id = id;
            race.Title = raceVM.Title;
            race.Description = raceVM.Description;
            race.AddressId = raceVM?.AddressId;
            race.Address = raceVM.Address;

            _raceRepository.Update(race);

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            var raceDetails = await _raceRepository.GetByIdAsync(id);

            if (raceDetails == null) return View("Error");

            return View(raceDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteRace(int id)
        {
            var clubdetails = await _raceRepository.GetByIdAsync(id);

            if(clubdetails == null) return View("error");

            _raceRepository.Delete(clubdetails);

            return RedirectToAction("Index");
        }
        #endregion

        #region // Create - Prima di PhotoServices
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public async Task<IActionResult> Create(Race race)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(race);
        //    }

        //    _raceRepository.Add(race);

        //    return RedirectToAction("Index");
        //}
        #endregion

        #region // Prima di implementare Interfaces & Repository

        /*private readonly ApplicationDbContext _context;

        public RaceController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var races = _context.Races.ToList();
            return View(races);
        }

        public IActionResult Detail(int id) 
        {
            var race = _context.Races.Include(a => a.Address).FirstOrDefault(r => r.Id == id);

            return View(race);
        }*/
        #endregion
    }
}

ProgettoTest/Views/Dashboard/EditUserProfile.cshtml
@using ProgettoTest.ViewModels
@model EditUserDashboardViewModel


<form asp-action="EditUserProfile" method="post" class="row" enctype="multipart/form-data">
    <input type="hidden" id="Id" name="Id" asp-for="Id" />
    <div class="col-6">
        <div class="form-group">
            <label asp-for="City">City:</label>
            <input asp-for="City" type="text" class="form-control form-control-lg" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            <label asp-for="State">State:</label>
            <input asp-for="State" type="text" class="form-control form-control-lg" />
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            <label asp-for="Pace">Pace:</label>
            <input asp-for="Pace" type="text" class="form-control form-control-lg" />
            <span asp-validation-for="Pace" class="text-danger"></span>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            <label asp-for="Mileage">Mileage:</label>
            <input asp-for="Mileage" type="text" class="form-control form-control-lg" />
            <span asp-validation-for="Mileage" class="text-danger"></span>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            <label asp-for="Image">Image:</label>
            <input asp-for="Image" type="file" class="form-control form-control-lg" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
    </div>
    <div class="col-12">
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Save changes</button>
        </div>
    </div>
</form>

ProgettoTest/Views/Dashboard/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using ProgettoTest.ViewModels

@inject SignInManager<AppUser> SignInManager

@model DashboardViewModel

<h1 class="display-4 fw-normal">User Dashboard</h1>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Club" asp-action="Create">Create Club</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Race" asp-action="Create">Create Race</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Dashboard" asp-action="EditUserProfile">Edit User Profile</a>
<div class="album py-5 bg-light">
    <div class="container">
        <h2 class="display-4 fw-normal">Your races</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            @foreach (var item in Model.Races)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="Race" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Race" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.RaceCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <h2 class="display-4 fw-normal">Your Clubs</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Clubs)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="Club" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Club" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.ClubCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>
</div>